"""create initial tables

Revision ID: 7378756b2e0b
Revises: 
Create Date: 2025-07-20 00:16:37.375913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7378756b2e0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_game_stats_id'), 'game_stats', ['id'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_goal_details_id'), 'goal_details', ['id'], unique=False)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_mom_votes_id'), 'mom_votes', ['id'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_index(op.f('ix_team_players_id'), 'team_players', ['id'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_team_players_id'), table_name='team_players')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_mom_votes_id'), table_name='mom_votes')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_goal_details_id'), table_name='goal_details')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_game_stats_id'), table_name='game_stats')
    # ### end Alembic commands ###
